administer settings configuration:
  title: 'Administer settings configuration'

edit settings data:
  title: 'Edit settings data'

view settings overview:
  title: 'View settings overview'

permission_callbacks:
  - \Drupal\ref_settings\SettingsPermissions::settingsTypePermissions