services:
  paramconverter.settings:
    class: Drupal\ref_settings\ParamConverter\SettingsConverter
    tags:
      - { name: paramconverter }

  ref_settings.subscriber:
    class: Drupal\ref_settings\Routing\SettingsRouteSubscriber
    tags:
      - { name: event_subscriber }